name: Latest blog post workflow

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "5"
          feed_list: "https://medium.com/feed/@wendreof"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
          committer_name: "github-actions[bot]"
